# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ccd755cad3bfa5ff159a2893c7d1b315eeb405f3eb15ad8d8e6f5b3b60d029e341353ca142065d821590f085589c42de586306dcd1f7ba76a6c6a1737361ef48

test:
  secret_key_base: c5cae45c08ceb92dcf86acf776119af7ddd9d2ccd6ce0b9d39f40436d4a769f1a8b2ef690121fa26a204c41bc6675be56b633810bf7b8d76942f5ee14d67b18a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
